version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: buildingdb
      POSTGRES_USER: buildinguser
      POSTGRES_PASSWORD: buildingpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: