definitions:
  model.Building:
    properties:
      city:
        type: string
      floor_count:
        type: integer
      id:
        type: integer
      name:
        type: string
      year:
        type: integer
    required:
    - city
    - floor_count
    - name
    - year
    type: object
info:
  contact: {}
paths:
  /buildings:
    get:
      consumes:
      - application/json
      description: Get list of buildings with optional filters
      parameters:
      - description: City filter
        in: query
        name: city
        type: string
      - description: Year filter
        in: query
        name: year
        type: integer
      - description: Floor count filter
        in: query
        name: floor_count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Building'
            type: array
      summary: List buildings
      tags:
      - buildings
    post:
      consumes:
      - application/json
      description: Add a new building to the database
      parameters:
      - description: Building Info
        in: body
        name: building
        required: true
        schema:
          $ref: '#/definitions/model.Building'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Building'
      summary: Create a new building
      tags:
      - buildings
swagger: "2.0"
